name: Production
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_TITLE: ${{ vars.TITLE }}
      REACT_APP_DESCRIPTION: ${{ vars.DESCRIPTION }} 
      REACT_APP_KEYWORDS: ${{ vars.KEYWORDS }} 
      REACT_APP_URL: ${{ vars.URL }} 
      REACT_APP_THEME_COLOR: ${{ vars.THEME_COLOR }} 
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        yarn
        yarn build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: reggionick/s3-deploy@v3
      with:
        folder: build
        bucket: ${{ secrets.BUCKET }}
        bucket-region: us-east-1