name: Production
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check the branch
      if: github.ref != 'refs/heads/master'
      run: exit 1
    - name: Move on
      run: exit 0
  deploy:
    runs-on: ubuntu-latest
    if: always()
    needs: [ setup ]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_TITLE: ${{ vars.TITLE }}
      REACT_APP_DESCRIPTION: ${{ vars.DESCRIPTION }} 
      REACT_APP_KEYWORDS: ${{ vars.KEYWORDS }} 
      REACT_APP_URL: ${{ vars.URL }} 
      REACT_APP_THEME_COLOR: ${{ vars.THEME_COLOR }} 
    steps:
    - name: Get latest
      run: 'ls'
    - name: Yarn Install
      run: 'yarn'
    - name: Yarn Build
      run: 'yarn build'
    - name: deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: build
        bucket: ${{ secrets.BUCKET }}
        bucket-region: us-east-1